import time
import math
# PROBLEM 1


# If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9.
# The sum of these multiples is 23. Find the sum of all the multiples of 3 or 5 below 1000.

def solution(number):
    total_sum = 0
    for x in range(number):
        if x % 3 == 0 or x % 5 == 0:
            total_sum = total_sum + x
    print(total_sum)


# PROBLEM 2


# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.
def fibonacci(number):
    array = [0, 1]
    even = []
    odd = []
    for x in range(number - 1):
        f = array[-1] + array[-2]
        array.append(f)
        if f % 2 == 0:
            even.append(f)
        else:
            odd.append(f)
    print(array)

# PROBLEM 3
# The prime factors of 13195 are 5, 7, 13 and 29.
# What is the largest prime factor of the number 600851475143?

    def prime(number):
        prime_array = []
        for x in range(2, number // 2):
            if number % x == 0:
                prime_array.append(x)
                p = number // x
                prime(p)
        prime_array.sort()
        print(prime_array)

# A palindromic number reads the same both ways.
# The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.
# Find the largest palindrome made from the product of two 3-digit numbers.


def palindrome(palinrange):
    for number_being_checked in range(palinrange):
        number_being_checked = str(number_being_checked)
        if list(number_being_checked) == list(reversed(list(number_being_checked))):
            number_being_checked = int(number_being_checked)
            for i in range(100, 999):
                if number_being_checked % i == 0:
                    y = number_being_checked / i
                    if (y > 100) and (y < 1000):
                        print(number_being_checked)








# M A I N #

start = time.time()
problem11()
end = time.time()
print("finished in", round(end - start, 2), "seconds")
